version: "3.8"

services:


  configserver:
    image: pukala93/bank_configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - pukala93_bank
     
  eurekaserver:
    image: pukala93/bank_eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - pukala93_bank
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  accounts:
    image: pukala93/bank_accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - pukala93_bank
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
  
  loans:
    image: pukala93/bank_loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - pukala93_bank
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    
  cards:
    image: pukala93/bank_cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - pukala93_bank
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
   

networks:
  pukala93_bank: